---
title: "5.4.3. How to model DOE data"
author: "Robert A. Stevens"
date: "`r Sys.Date()`"
output: github_document
---

https://www.itl.nist.gov/div898/handbook/pri/section4/pri43.htm

*DOE models should be consistent with the goal of the experiment*

In general, the trial model that will be fit to DOE data should be consistent with the goal of the experiment and has been predetermined by the goal of the experiment and the experimental design and data collection methodology.

*Comparative designs*

Models were given earlier for comparative designs:

- completely randomized designs
    + https://www.itl.nist.gov/div898/handbook/pri/section3/pri331.htm#Model%20for%20a

- randomized block designs
    + https://www.itl.nist.gov/div898/handbook/pri/section3/pri332.htm#Model%20for%20a

- Latin square designs
    + https://www.itl.nist.gov/div898/handbook/pri/section3/pri3321.htm#Latin%20square

*Full factorial designs*

For full factorial designs with k factors (2^k runs, not counting any center points or replication runs), the full model contains all the main effects and all orders of interaction terms. Usually, higher-order (three or more factors) interaction terms are included initially to construct the normal (or half-normal) plot of effects, but later dropped when a simpler, adequate model is fit. Depending on the software available or the analyst's preferences, various techniques such as normal or half-normal plots, Youden plots, p-value comparisons and stepwise regression routines are used to reduce the model to the minimum number of needed terms. An example of model selection is shown later in this section:

https://www.itl.nist.gov/div898/handbook/pri/section4/pri471.htm#Step%202:%20Create%20theTheoretical

and an example of Yates algorithm is given as a case study:

https://www.itl.nist.gov/div898/handbook/pri/section6/pri615.htm

*Fractional factorial designs*

For fractional factorial screening designs, it is necessary to know the alias structure in order to write an appropriate starting model  containing only the interaction terms the experiment was designed to estimate (assuming all terms confounded with these selected terms are insignificant). This is illustrated by the fractional factorial example later in this section:

https://www.itl.nist.gov/div898/handbook/pri/section4/pri472.htm#Step%202:%20Create%20the%20Theoretical

The starting model is then possibly reduced by the same techniques described above for full factorial models.

*Response surface designs*

Response surface initial models include quadratic terms and may occasionally also include cubic terms. These models were described in section 3:

https://www.itl.nist.gov/div898/handbook/pri/section3/pri336.htm

*Model validation*

Of course, as in all cases of model fitting, residual analysis and other tests of model fit are used to confirm or adjust models, as needed:

https://www.itl.nist.gov/div898/handbook/pri/section4/pri44.htm
